// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9UbjP_IKvBySM9UwnQVS50gM6fXw0Wio',
    appId: '1:184678689438:web:051a63531412b4a1d3e98f',
    messagingSenderId: '184678689438',
    projectId: 'face-app-e6949',
    authDomain: 'face-app-e6949.firebaseapp.com',
    storageBucket: 'face-app-e6949.firebasestorage.app',
    measurementId: 'G-FX01RJ23Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpksS07jXHlWnpPIbElBfU7oW0NLTCQLA',
    appId: '1:184678689438:android:7237708ff26f61cdd3e98f',
    messagingSenderId: '184678689438',
    projectId: 'face-app-e6949',
    storageBucket: 'face-app-e6949.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZaJL5L_iU-8m-FordhcuHe7zI-FSX3uU',
    appId: '1:184678689438:ios:c657593707f6c5d8d3e98f',
    messagingSenderId: '184678689438',
    projectId: 'face-app-e6949',
    storageBucket: 'face-app-e6949.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );
}
